plugin "azurerm" {
    enabled = true
    version = "0.19.0"
    source  = "github.com/terraform-linters/tflint-ruleset-azurerm"
}

plugin "terraform" {
  enabled = true
  preset  = "all"
}

rule "terraform_naming_convention" {
  enabled = true
  format = "snake_case"

  resource {
    format = "cdktf_snake_case"
  }

  custom_formats = {
    cdktf_snake_case = {
      description = "Snake case ending with the 8-character hash auto-generated by the CDK"
      regex = "^[a-z][a-z0-9]*(_[a-z0-9]+)*_[A-Z0-9]{8}$"
    }
  }
}
