name: CI workflow

on: [push, pull_request]

jobs:
  pre-commit:
    name: Run pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0

  tests:
    name: Jest tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - name: Run Jest tests
        run: npm test
      - name: Upload coverage information
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage/

  bridgecrew:
    name: Scan IaC code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Node packaged
        run: npm install -g cdktf-cli@next && npm install -g ts-node@10.9.1 && npm install
      - name: Synthesize Terraform template and convert to HCL2
        run: $GITHUB_WORKSPACE/src/resources/hcl2-convert.sh
      - name: Run Bridgecrew scan
        id: Bridgecrew
        uses: bridgecrewio/bridgecrew-action@v1.2229.0
        with:
          api-key: ${{ secrets.BRIDGECREW_API_KEY }}
          directory: /home/runner/work/azure-sql-server/azure-sql-server/cdktf.out/
          soft_fail: true
          framework: terraform
          output_format: cli
          quiet: false
          download_external_modules: true

  costs:
    name: Get resource costs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    env:
      TF_ROOT: /home/runner/work/azure-sql-server/azure-sql-server/cdktf.out/stacks/cdktf/
      INFRACOST_TERRAFORM_CLOUD_TOKEN: ${{ secrets.TFC_TOKEN }}
      INFRACOST_TERRAFORM_CLOUD_HOST: app.terraform.io

    steps:
      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: "${{ github.event.pull_request.base.ref }}"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Node packaged
        run: npm install -g cdktf-cli@next && npm install -g ts-node@10.9.1 && npm install
      - name: Synthesize Terraform template
        run: cdktf get && cdktf synth

      # Generate Infracost JSON file as the baseline.
      - name: Generate Infracost cost estimate baseline
        run: |
          infracost breakdown --path=${TF_ROOT} \
                              --format=json \
                              --out-file=/tmp/infracost-base.json

      - name: Post Infracost comment
        run: |
          infracost comment github --path=/tmp/infracost-base.json \
                                   --repo=$GITHUB_REPOSITORY \
                                   --github-token=${{ secrets.GITHUB_TOKEN }} \
                                   --commit=$GITHUB_SHA \
                                   --behavior=update

  vale:
    name: Run Vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@v2.0.1
        with:
          debug: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [pre-commit, tests, vale, bridgecrew, costs]
    if: ${{ needs.pre-commit.result == 'success' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: 14.18.1
          registry-url: "https://npm.pkg.github.com"
          scope: "@shahradr"
      - name: Release
        run: npx semantic-release@v18.0.0
